name: Build and release
on: workflow_dispatch
jobs:
  release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: pwsh -File ci/build.ps1
        env:
          REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
permissions:
  contents: write
